name: Go CLI CI
on:
  push:
    paths:
      - "cli/**"
      - ".github/workflows/go-cli.yml"
      - "README.md"
      - "ARCHITECTURE.md"
  pull_request:
    paths:
      - "cli/**"
      - ".github/workflows/go-cli.yml"
      - "README.md"
      - "ARCHITECTURE.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Build CLI
        run: |
          cd cli
          go build -v ./...
      - name: Run CLI Unit Tests
        run: |
          cd cli
          go test -v ./...
